### ISSUE TITLE
how to handle client certificates with pactumjs

### ISSUE THREAD

**Issue by madvi30477** [pactumjs/pactum#310]
**Copied From Title**
@ASaiAnudeep and @leelaprasadv can Pactum Mock Server handles https requests and will it be able to handle client certificates with pfx format . i am using pactum 3.6.0 version but still facing issues while using mock server with https requests. and would like to know more about how to handle client certificates with pactumjs.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by madvi30477** [comment]
Hi, 
Could you please let me know how to make a post call using mock server. i have set up mock defaults by adding .crt and .key files but getting 500 internal error while making post call using pactum.spec(). 

Thanks,
Madhavi

**Comment by leelaprasadv** [comment]
Hi @madvi30477,

There could be multiple reasons for Internal server error. 

Typically Internal server error HTTP 500 is due to unhandled server side issue while fulfilling a request. Also it is difficult to help or troubleshoot the issue with just above details. It is not clear if the requests are made purely to the local mock server or a remote web server
Can post the sample code/setup closest to your implementation to help better?

Here are some examples that you can refer
https://github.com/pactumjs/pactum-examples/blob/main/pactum-demo/component-testing/tests/order.test.js

For more details please check the documentation on API and component testing https://pactumjs.github.io/guides/component-testing.html

**Comment by madvi30477** [comment]
Hi @leelaprasadv : Thanks for sharing above info, I have tried the options and now getting  AssertionError [ERR_ASSERTION]: 
Error in Console: 
Interaction not exercised: POST. 
await spec()
  .useInteraction({
    request: {
      method: 'POST',
      path: '/user/32'
    },
    response: {
      status: 201
    
  })
  .post('https://localhost:443/vendor/certificate/server'
    
  })
  .expectStatus(201)
})

Note: Have given sample host and address but code remains same. 
const mockOpts = {port: 3001, host: '127.0.0.1'};
await mock.setDefaults(mockOpts)

**Comment by leelaprasadv** [comment]
Hi @madvi30477,

There could be multiple reasons for Internal server error. 

Typically Internal server error HTTP 500 is due to unhandled server side issue while fulfilling a request. Also it is difficult to help or troubleshoot the issue with just above details. It is not clear if the requests are made purely to the local mock server or a remote web server
Can post the sample code/setup closest to your implementation to help better?

Here are some examples that you can refer
https://github.com/pactumjs/pactum-examples/blob/main/pactum-demo/component-testing/tests/order.test.js

For more details please check the documentation on API and component testing https://pactumjs.github.io/guides/component-testing.html

**Comment by leelaprasadv** [comment]
@madvi30477 
It seems you are trying to run the mock server on port `3001` and trying to hit the mock server on `443` port which will result in interaction not found. Update the port to be similar and try again.

**Comment by madvi30477** [comment]
@leelaprasadv : In fact i did not set up any default port , i set up only host in defaults but i could see in console as below. my host is azure api .
console :
Agent {
  _events: [Object: null prototype] {
    free: [Function (anonymous)],
    newListener: [Function: maybeEnableKeylog]
  },
  _eventsCount: 2,
  _maxListeners: undefined,
  defaultPort: 443,
  protocol: 'https:',
  options: [Object: null prototype] {
    cert: 'C:\\Pactum_SingleSpec\\CucumberLibrary\\TestDependencies\\API\\Cert.crt',
    key: 'C:\\Pactum_SingleSpec\\CucumberLibrary\\TestDependencies\\API\\Key.key',
    rejectUnauthorized: false,
    noDelay: true,
    path: null
  },
  requests: [Object: null prototype] {},
  sockets: [Object: null prototype] {},
  freeSockets: [Object: null prototype] {},
  keepAliveMsecs: 1000,
  keepAlive: false,
  maxSockets: Infinity,
  maxFreeSockets: 256,
  scheduling: 'lifo',
  maxTotalSockets: Infinity,
  totalSocketCount: 0,
  maxCachedSessions: 100,
  _sessionCache: { map: {}, list: [] },
  [Symbol(kCapture)]: false
}

Error :   × failed
      AssertionError [ERR_ASSERTION]: Interaction not exercised: POST - https://cvvvvfsdsada555.azure-api.net/vendor/order/certificate/server

Code :
const keyFilePath = path.join(homeDirectory, `TestDependencies/API/Key.key`);
    const certFilePath = path.join(homeDirectory, `TestDependencies/API/Cert.crt`);
    //mock.start(443);
    const agent = new https.Agent({
        cert: certFilePath,
        key: keyFilePath,
        rejectUnauthorized: false // Ignore self-signed certificate errors
      });
    const mockOpts = {host: 'cvvvvfsdsada555.azure-api.net/vendor/order/certificate/server', httpsOpts: {key: keyFilePath, cert: certFilePath}};
    await mock.setDefaults(mockOpts);
    //mock.start();
    if (typeof (fileContent) === "string") {
        console.log('Req ID',this.requestID);
        fileContent=fileContent.replace('TestRequestID',this.requestID);
  
     this.spec2 = pactum.spec()
    .useInteraction({
        request: {
            method: 'POST',
            path: 'https:// cvvvvfsdsada555.azure-api.net/vendor/order/certificate/server',
            queryParams: { RequestId: this.requestID }
        },
        response: {
            status: 201
            
        }
    })
    .withBearerToken(this.token)
    .withHeaders("Content-Type", "application/xml")
    .withHeaders("Accept", "application/xml")
    .withBody(fileContent)
    .post('https:// cvvvvfsdsada555.azure-api.net/vendor/order/certificate/server)
    //.expectStatus(201);
        
        
    }

    console.log('mockrespons',this.spec2.toss());
   
});

Note : host address  i have given sample for your reference. Not sure what i missed here, could you please help me to resolve issue with mock server interactions.

**Comment by leelaprasadv** [comment]
I see couple of issues with above setup

1. Mock server in pactum is a local server (to simulate external API interactions for service under test - SUT in a component test setup) so it can only support/run on local IP addresses on the machine (ex: `localhost`, `127.0.0.1`, `0.0.0.0` etc). Use of external server hostname in URL cannot be used, as the calls made to remote server cannot be trapped and routed to mock server - that is not how mock server works. 
2. When you add a mock interaction, it should be called/exercised. If not, above error will be displayed. In the above case, as the mock interaction is not called, removing the interaction will solve the error.

Hope this helps resolve the issue!
